module.exports = {
  "Services": {
    "Desktop snapshot": {
      "1": "<ul class=\"navcard-wrapper\"\n  data-test=\"navcard-list-component\">\n  <li class=\"navcard\">\n    <a href=\"/topic/uitest-hat-works\">\n      <h3 class=\"navcard__title\">UITEST: Hat Works</h3>\n      <p class=\"navcard__teaser\">The Hat Works is the UK's only museum dedicated\n        to the hatting industry, hats and headwear.</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/council-tax\">\n      <h3 class=\"navcard__title\">Council Tax</h3>\n      <p class=\"navcard__teaser\">How to pay, discounts - </p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/test-topic\">\n      <h3 class=\"navcard__title\">Test topic</h3>\n      <p class=\"navcard__teaser\">this is a test</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/main-topic\">\n      <h3 class=\"navcard__title\">Main Topic </h3>\n      <p class=\"navcard__teaser\">This is the main topic</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/test-topic2\">\n      <h3 class=\"navcard__title\">test topic2</h3>\n      <p class=\"navcard__teaser\">This is a test teaser</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/bins-and-recycling\">\n      <h3 class=\"navcard__title\">Bins &amp; Recycling</h3>\n      <p class=\"navcard__teaser\">Collection days, bulky items</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/libraries\">\n      <h3 class=\"navcard__title\">Libraries</h3>\n      <p class=\"navcard__teaser\">Reserve or renew, book a computer</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/benefits-and-support\">\n      <h3 class=\"navcard__title\">Benefits &amp; Support</h3>\n      <p class=\"navcard__teaser\">Benefits &amp; Support</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/work-and-jobs\">\n      <h3 class=\"navcard__title\">Work &amp; Jobs</h3>\n      <p class=\"navcard__teaser\">Find work, career &amp; training advice</p>\n    </a>\n\n  </li>\n</ul>"
    },
    "Mobile snapshot": {
      "1": "<ul class=\"navcard-wrapper\"\n  data-test=\"navcard-list-component\">\n  <li class=\"navcard\">\n    <a href=\"/topic/uitest-hat-works\">\n      <h3 class=\"navcard__title\">UITEST: Hat Works</h3>\n      <p class=\"navcard__teaser\">The Hat Works is the UK's only museum dedicated\n        to the hatting industry, hats and headwear.</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/council-tax\">\n      <h3 class=\"navcard__title\">Council Tax</h3>\n      <p class=\"navcard__teaser\">How to pay, discounts - </p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/test-topic\">\n      <h3 class=\"navcard__title\">Test topic</h3>\n      <p class=\"navcard__teaser\">this is a test</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/main-topic\">\n      <h3 class=\"navcard__title\">Main Topic </h3>\n      <p class=\"navcard__teaser\">This is the main topic</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/test-topic2\">\n      <h3 class=\"navcard__title\">test topic2</h3>\n      <p class=\"navcard__teaser\">This is a test teaser</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/bins-and-recycling\">\n      <h3 class=\"navcard__title\">Bins &amp; Recycling</h3>\n      <p class=\"navcard__teaser\">Collection days, bulky items</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/libraries\">\n      <h3 class=\"navcard__title\">Libraries</h3>\n      <p class=\"navcard__teaser\">Reserve or renew, book a computer</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/benefits-and-support\">\n      <h3 class=\"navcard__title\">Benefits &amp; Support</h3>\n      <p class=\"navcard__teaser\">Benefits &amp; Support</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/work-and-jobs\">\n      <h3 class=\"navcard__title\">Work &amp; Jobs</h3>\n      <p class=\"navcard__teaser\">Find work, career &amp; training advice</p>\n    </a>\n\n  </li>\n</ul>"
    },
    "Tablet snapshot": {
      "1": "<ul class=\"navcard-wrapper\"\n  data-test=\"navcard-list-component\">\n  <li class=\"navcard\">\n    <a href=\"/topic/uitest-hat-works\">\n      <h3 class=\"navcard__title\">UITEST: Hat Works</h3>\n      <p class=\"navcard__teaser\">The Hat Works is the UK's only museum dedicated\n        to the hatting industry, hats and headwear.</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/council-tax\">\n      <h3 class=\"navcard__title\">Council Tax</h3>\n      <p class=\"navcard__teaser\">How to pay, discounts - </p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/test-topic\">\n      <h3 class=\"navcard__title\">Test topic</h3>\n      <p class=\"navcard__teaser\">this is a test</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/main-topic\">\n      <h3 class=\"navcard__title\">Main Topic </h3>\n      <p class=\"navcard__teaser\">This is the main topic</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/test-topic2\">\n      <h3 class=\"navcard__title\">test topic2</h3>\n      <p class=\"navcard__teaser\">This is a test teaser</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/bins-and-recycling\">\n      <h3 class=\"navcard__title\">Bins &amp; Recycling</h3>\n      <p class=\"navcard__teaser\">Collection days, bulky items</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/libraries\">\n      <h3 class=\"navcard__title\">Libraries</h3>\n      <p class=\"navcard__teaser\">Reserve or renew, book a computer</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/benefits-and-support\">\n      <h3 class=\"navcard__title\">Benefits &amp; Support</h3>\n      <p class=\"navcard__teaser\">Benefits &amp; Support</p>\n    </a>\n\n  </li>\n  <li class=\"navcard\">\n    <a href=\"/topic/work-and-jobs\">\n      <h3 class=\"navcard__title\">Work &amp; Jobs</h3>\n      <p class=\"navcard__teaser\">Find work, career &amp; training advice</p>\n    </a>\n\n  </li>\n</ul>"
    }
  },
  "__version": "12.13.0"
}
