module.exports = {
  "__version": "12.13.0",
  "Home": {
    "search-and-top-tasks - Compare structure snapshot": {
      "1": "<section class=\"section top-tasks-wrapper\"\n  data-test=\"search-and-top-tasks\">\n  <div class=\"grid-container\">\n    <div class=\"grid-100\">\n      <h1\n        class=\"section__title section__title--padded-bottom--m section__title--margin-top h-xl\">\n        Welcome to Stockport</h1>\n      <section class=\"search-bar\">\n        <h2 class=\"visuallyhidden\">Search stockport.gov.uk</h2>\n\n        <form aria-label=\"website search\"\n          action=\"\"\n          method=\"get\"\n          role=\"search\"\n          id=\"cludo-search-hero-form\"\n          class=\"cludo-search_autocomplete\">\n          <label class=\"visuallyhidden\"\n            for=\"cludo-search-bar\">\n            search input box\n          </label>\n          <input class=\"grid-100 tablet-grid-100 mobile-grid-100 search-input\"\n            id=\"cludo-search-bar\"\n            type=\"text\"\n            name=\"query\"\n            placeholder=\"Search on stockport.gov.uk\"\n            autocomplete=\"off\">\n          <button value=\"Submit search\"\n            class=\"search-button\"\n            type=\"submit\"><span class=\"fa fa-search\"\n              aria-hidden=\"true\"></span><span class=\"visuallyhidden\"> Submit\n              Search</span></button>\n        </form>\n      </section>\n\n      <div class=\"top-tasks-placeholder placeholder\">\n        <h2>Top tasks</h2>\n      </div>\n    </div>\n  </div>\n  <div class=\"skyline-wrapper\"></div>\n</section>"
    },
    "navcard-list - Compare structure snapshot": {
      "1": "<div class=\"grid-100\"\n  data-test=\"navcard-list\">\n  <h2 class=\"section__title section__title--padded-bottom h-l\">Our services</h2>\n\n  <ul class=\"navcard-wrapper\">\n    <li class=\"navcard\">\n      <a href=\"/topic/uitest-hat-works\">\n        <h3 class=\"navcard__title\">UITEST: Hat Works</h3>\n        <p class=\"navcard__teaser\">The Hat Works is the UK's only museum\n          dedicated to the hatting industry, hats and headwear.</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/council-tax\">\n        <h3 class=\"navcard__title\">Council Tax</h3>\n        <p class=\"navcard__teaser\">How to pay, discounts - </p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/test-topic\">\n        <h3 class=\"navcard__title\">Test topic</h3>\n        <p class=\"navcard__teaser\">this is a test</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/main-topic\">\n        <h3 class=\"navcard__title\">Main Topic </h3>\n        <p class=\"navcard__teaser\">This is the main topic</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/test-topic2\">\n        <h3 class=\"navcard__title\">test topic2</h3>\n        <p class=\"navcard__teaser\">This is a test teaser</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/bins-and-recycling\">\n        <h3 class=\"navcard__title\">Bins &amp; Recycling</h3>\n        <p class=\"navcard__teaser\">Collection days, bulky items</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/libraries\">\n        <h3 class=\"navcard__title\">Libraries</h3>\n        <p class=\"navcard__teaser\">Reserve or renew, book a computer</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/benefits-and-support\">\n        <h3 class=\"navcard__title\">Benefits &amp; Support</h3>\n        <p class=\"navcard__teaser\">Benefits &amp; Support</p>\n      </a>\n\n    </li>\n    <li class=\"navcard\">\n      <a href=\"/topic/work-and-jobs\">\n        <h3 class=\"navcard__title\">Work &amp; Jobs</h3>\n        <p class=\"navcard__teaser\">Find work, career &amp; training advice</p>\n      </a>\n\n    </li>\n  </ul>\n\n  <div class=\"featured-content-button-wrapper\">\n    <a class=\"button button-outline button-partialrounded button-call-to-action\"\n      href=\"#\">View more services</a>\n  </div>\n</div>"
    },
    "global-alert - Compare structure snapshot": {
      "1": "<div data-test=\"global-alert\">\n\n  <div class=\"global-alert-error\">\n    <div class=\"grid-container grid-100 global-alert-container\">\n      <div\n        class=\"grid-100 mobile-grid-100 tablet-grid-100 global-alert grid-parent\">\n        <div\n          class=\"hide-on-mobile hide-on-tablet global-alert-icon global-alert-icon-error\">\n          <i></i>\n        </div>\n        <div class=\"grid-80 mobile-grid-95 global-alert-text-container\">\n          <div class=\"global-alert-text-error\">\n            <h3>Alert error</h3>\n            <p><a href=\"https://www.stockport.gov.uk\"\n                title=\"body text\">body text</a></p>\n\n          </div>\n        </div>\n        <div class=\"global-alert-close-container\">\n          <a href=\"javascript:void(0)\"\n            title=\"Close Alert error alert\"\n            aria-label=\"Close Alert error alert\">\n            <div class=\"global-alert-close-error\">\n              <i class=\"close-alert\"\n                data-slug=\"alert-error\"\n                data-parent=\"global-alert-error\"></i>\n            </div>\n          </a>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <script>\n    require(['/assets/javascript/config-fd0642d6.min.js'], function() {\n      require(['alerts'],\n        function(alerts) {\n          alerts.Init();\n        }\n      );\n    });\n  </script>\n</div>"
    },
    "personalised-services - Compare structure snapshot": {
      "1": "<section class=\"personalised-services\"\n  data-test=\"personalised-services\">\n  <h2 class=\"visuallyhidden\">Subscription </h2>\n  <div class=\"grid-container\">\n    <div class=\"grid-100 enhanced_service\"\n      id=\"test-email-alerts\">\n      <p>Get the latest news and information about your council services\n        straight to your inbox</p>\n\n      <form method=\"get\"\n        role=\"form\"\n        action=\"/subscribe\">\n        <div>\n          <label class=\"subscribe-label\"\n            for=\"emailAddress\">\n            Enter your email address\n          </label>\n          <input class=\"subscribe-input\"\n            type=\"text\"\n            id=\"emailAddress\"\n            name=\"emailAddress\">\n          <button type=\"submit\"\n            id=\"test-subscribe\"\n            class=\"button-default\">Subscribe</button>\n        </div>\n      </form>\n    </div>\n  </div>\n</section>"
    }
  }
}
