global using Amazon.Runtime;
global using Amazon.SimpleEmail;
global using Amazon.SimpleEmail.Model;
global using FluentAssertions;
global using Markdig.Helpers;
global using Microsoft.AspNetCore.DataProtection;
global using Microsoft.AspNetCore.DataProtection.Repositories;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Http.Features;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Abstractions;
global using Microsoft.AspNetCore.Mvc.Controllers;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using Microsoft.AspNetCore.Mvc.ViewComponents;
global using Microsoft.Extensions.Primitives;
global using Microsoft.Net.Http.Headers;
global using Microsoft.FeatureManagement;
global using Moq;
global using Newtonsoft.Json;
global using StockportGovUK.NetStandard.Gateways.CivicaPay;
global using StockportGovUK.NetStandard.Gateways.Models.Civica.Pay.Request;
global using StockportGovUK.NetStandard.Gateways.Models.Civica.Pay.Response;
global using StockportGovUK.NetStandard.Gateways.Response;
global using StockportWebapp.Client;
global using StockportWebapp.ContentFactory;
global using StockportWebapp.Controllers;
global using StockportWebapp.DataProtection;
global using StockportWebapp.Filters;
global using StockportWebapp.Middleware;
global using StockportWebapp.Models;
global using StockportWebapp.Models.Config;
global using StockportWebapp.Models.Enums;
global using StockportWebapp.Models.Exceptions;
global using StockportWebapp.Models.Groups;
global using StockportWebapp.Models.ProcessedModels;
global using StockportWebapp.Models.Responses;
global using StockportWebapp.Models.Validation;
global using StockportWebapp.Repositories;
global using StockportWebapp.RSS;
global using StockportWebapp.Services;
global using StockportWebapp.TagParsers;
global using StockportWebapp.Utils;
global using StockportWebapp.Utils.Extensions;
global using StockportWebapp.ViewComponents;
global using StockportWebapp.ViewModels;
global using StockportWebappTests_Unit.Builders;
global using StockportWebappTests_Unit.Helpers;
global using StockportWebappTests_Unit.Unit.TestBuilders;
global using StockportWebappTests_Unit.Unit.Utils;
global using System.Collections;
global using System.ComponentModel.DataAnnotations;
global using System.Net;
global using System.Text;
global using System.Xml.Linq;
global using Xunit;
global using HostString = Microsoft.AspNetCore.Http.HostString;
global using PathString = Microsoft.AspNetCore.Http.PathString;
global using QueryString = Microsoft.AspNetCore.Http.QueryString;
global using HttpResponse = StockportWebapp.Client.HttpResponse;
global using DataProtectionBuilderExtensions = StockportWebapp.DataProtection.DataProtectionBuilderExtensions;
global using Group = StockportWebapp.Models.Groups.Group;
